name: Test
on:
  push:
    branches:
      - master
  pull_request:
env:
  TELEGRAM_TOKEN: ${{ secrets.TEST_TELEGRAM_TOKEN }}
  TEST_CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
  TEST_EMAIL_PWD: ${{ secrets.TEST_EMAIL_PWD }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml build
          docker-compose --file docker-compose.test.yml run test
